### ISSUE TITLE
Can't add content / posts

### ISSUE THREAD

**Issue by michaelmoussa** [GraphStory/graph-kit-php#3]
Looks like `/posts/edit` is 404'ing, which is preventing **Add Content** from working.

![see screenshot](https://i.imgur.com/k3YkzoJ.png)

**Comment by jeremykendall** [comment]
Thanks so much for the bug report. I'm on the road today but will get it fixed up ASAP.

Adding the HTTP response preview to the screenshot was genius, BTW. Nicely done :-)
