### ISSUE TITLE
Show link to /posts instead of login form input for connected users

### ISSUE THREAD

**Issue by ikwattro** [GraphStory/graph-kit-php#8]
If you're connected, when you click on the GraphStory logo, you go back to the home page of the app.

However, in place of showing again the register and login input forms, it should be better to show a button to go to the /posts view, IMHO.

Preview here : 

![img](http://g.recordit.co/XvjbukVOcu.gif)

**Comment by jeremykendall** [comment]
Great idea, @ikwattro. I'll get it worked up.
